---
- name: Create
  hosts: localhost
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  tasks:
    - name: Get podman executable path # noqa: command-instead-of-shell
      ansible.builtin.shell: "command -v multipass"
      register: multipass_path
      changed_when: false
